language: python
python:
  - 2.7
sudo: required
dist: wheezy
install:
  - pip install -r requirements.txt
  - python setup.py develop
before_script:
  - sleep 3
script:
  - pybot -A tests/conf/default.args tests
